In [9]:
import json

with open("data/All_player_stats.json", "r", encoding="utf-8") as f:
    data1 = json.load(f)

print(type(data1))

if isinstance(data1, dict):
    print(data1.keys())

if isinstance(data1, list):
    print(data1[0])

<class 'dict'>
dict_keys(['LMP Simmons', 'RP Singh', 'RG Sharma', 'I Sharma', 'HH Pandya', 'JC Buttler', 'MR Marsh', 'AT Rayudu', 'KA Pollard', 'R Bhatia', 'S Gopal', 'M Ashwin', 'Harbhajan Singh', 'R Ashwin', 'R Vinay Kumar', 'MJ McClenaghan', 'AM Rahane', 'F du Plessis', 'JJ Bumrah', 'KP Pietersen', 'MA Agarwal', 'AD Russell', 'Q de Kock', 'UT Yadav', 'SS Iyer', 'JW Hastings', 'KK Nair', 'SV Samson', 'P Negi', 'C Munro', 'GB Hogg', 'PP Chawla', 'CR Brathwaite', 'CH Morris', 'NM Coulter-Nile', 'A Mishra', 'Z Khan', 'RV Uthappa', 'G Gambhir', 'MK Pandey', 'M Vijay', 'P Kumar', 'M Vohra', 'PJ Sangwan', 'JP Faulkner', 'S Ladda', 'RA Jadeja', 'DA Miller', 'DJ Bravo', 'GJ Maxwell', 'WP Saha', 'MP Stoinis', 'AR Patel', 'AJ Finch', 'Sandeep Sharma', 'BB McCullum', 'MG Johnson', 'SK Raina', 'MM Sharma', 'KD Karthik', 'P Sahu', 'Ishan Kishan', 'CH Gayle', 'A Nehra', 'V Kohli', 'B Kumar', 'AB de Villiers', 'Mustafizur Rahman', 'MC Henriques', 'KV Sharma', 'A Ashish Reddy', 'SR Watson', 'KM Jadhav', 'SN Khan', 'DA Warner', 'AF Milne', 'S Dhawan', 'Parvez Rasool', 'HV Patel', 'YS Chahal', 'NV Ojha', 'DJ Hooda', 'EJG Morgan', 'TG Southee', 'J Suchith', 'YK Pathan', 'SA Yadav', 'PA Patel', 'Kuldeep Yadav', 'SB Jakati', 'PV Tambe', 'SPD Smith', 'MS Dhoni', 'SE Marsh', 'J Yadav', 'M Morkel', 'Shakib Al Hasan', 'SP Narine', 'BB Sran', 'DS Kulkarni', 'KH Pandya', 'AD Nath', 'KJ Abbott', 'NLTC Perera', 'IK Pathan', 'Ankit Sharma', 'Mohammed Shami', 'D Wiese', 'S Aravind', 'JP Duminy', 'MJ Guptill', 'Bipul Sharma', 'KL Rahul', 'TM Head', 'STR Binny', 'KW Richardson', 'VR Aaron', 'Iqbal Abdulla', 'DW Steyn', 'T Shamsi', 'Imran Tahir', 'NS Naik', 'R Dhawan', 'AP Tare', 'DR Smith', 'R Sathish', 'JA Morkel', 'AB Dinda', 'S Nadeem', 'RR Pant', 'CA Lynn', 'JD Unadkat', 'SS Tiwary', 'S Kaushik', 'JO Holder', 'SW Billings', 'KS Williamson', 'Sachin Baby', 'Gurkeerat Singh', 'KC Cariappa', 'PSP Handscomb', 'SM Boland', 'Swapnil Singh', 'UT Khawaja', 'Yuvraj Singh', 'CJ Jordan', 'GJ Bailey', 'A Zampa', 'HM Amla', 'Anureet Singh', 'F Behardien', 'N Rana', 'UBT Chand', 'AS Rajpoot', 'BCJ Cutting', 'DL Chahar', 'ER Dwivedi', 'TA Boult', 'TS Mills', 'A Choudhary', 'Mandeep Singh', 'Rashid Khan', 'BA Stokes', 'JJ Roy', 'CR Woakes', 'MS Gony', 'T Natarajan', 'MK Tiwary', 'DT Christian', 'RD Chahar', 'PJ Cummins', 'Vishnu Vinod', 'B Stanlake', 'Basil Thampi', 'Tejas Baroka', 'SL Malinga', 'CJ Anderson', 'RA Tripathi', 'V Shankar', 'C de Grandhomme', 'S Badree', 'AJ Tye', 'SN Thakur', 'LH Ferguson', 'MM Patel', 'AD Mathews', 'Mohammad Nabi', 'S Kaul', 'Mohammed Siraj', 'K Rabada', 'Washington Sundar', 'SS Agarwal', 'NB Singh', 'DM Bravo', 'Ankit Soni', 'AR Bawne', 'SP Jackson', 'MN Samuels', 'R Tewatia', 'MJ Henry', 'Avesh Khan', 'IR Jaggi', 'E Lewis', 'MA Wood', 'M Markande', 'Mujeeb Ur Rahman', 'K Khejroliya', 'RK Singh', 'DJM Short', 'K Gowtham', 'B Laughlin', 'TK Curran', 'A Dananjaya', 'Shubman Gill', 'Shivam Mavi', 'H Klaasen', 'RK Bhui', 'JC Archer', 'LE Plunkett', 'PP Shaw', 'AD Hales', 'IS Sodhi', 'MK Lomror', 'L Ngidi', 'KM Asif', 'DJ Willey', 'DR Shorey', 'M Prasidh Krishna', 'MM Ali', 'P Chopra', 'JPR Scantlebury-Searles', 'Abhishek Sharma', 'S Lamichhane', 'CJ Dala', 'SP Goswami', 'KK Ahmed', 'SO Hetmyer', 'S Dube', 'Navdeep Saini', 'JM Bairstow', 'Rasikh Salam', 'CA Ingram', 'KMA Paul', 'N Pooran', 'SM Curran', 'CV Varun', 'GC Viljoen', 'GH Vihari', 'P Ray Barman', 'MJ Santner', 'JP Behrendorff', 'SC Kuggeleijn', 'AS Joseph', 'HF Gurney', 'S Midhun', 'SD Lad', 'R Parag', 'JL Denly', 'LS Livingstone', 'Arshdeep Singh', 'AJ Turner', 'SE Rutherford', 'Harpreet Brar', 'Y Prithvi Raj', 'O Thomas', 'AS Roy', 'S Sandeep Warrier', 'P Simran Singh', 'JL Pattinson', 'SS Cottrell', 'Ravi Bishnoi', 'A Nortje', 'T Banton', 'I Udana', 'D Padikkal', 'YBK Jaiswal', 'RD Gaikwad', 'TU Deshpande', 'KL Nagarkoti', 'Abdul Samad', 'PK Garg', 'JR Philippe', 'Kartik Tyagi', 'JDS Neesham', 'DR Sams', 'Shahbaz Ahmed', 'AT Carey', 'N Jagadeesan', 'JR Hazlewood', 'CJ Green', 'P Dubey', 'Monu Kumar', 'KA Jamieson', 'M Jansen', 'RM Patidar', 'C Sakariya', 'M Shahrukh Khan', 'JA Richardson', 'RP Meredith', 'Lalit Yadav', 'Virat Singh', 'LI Meriwala', 'Jalaj S Saxena', 'FA Allen', 'DJ Malan', 'KS Bharat', 'PWH de Silva', 'VR Iyer', 'Umran Malik', 'Akash Singh', 'GD Phillips', 'AK Markram', 'GHS Garton', 'K Yadav', 'NT Ellis', 'RV Patel', 'TL Seifert', 'Anmolpreet Singh', 'Anuj Rawat', 'IC Porel', 'AU Rashid', 'TH David', 'DP Conway', 'Tilak Varma', 'R Powell', 'OF Smith', 'Akash Deep', 'PBB Rajapaksa', 'RA Bawa', 'A Badoni', 'PVD Chameera', 'MS Wade', 'Mohsin Khan', 'A Manohar', 'R Shepherd', 'D Pretorius', 'Mukesh Choudhary', 'JM Sharma', 'VG Arora', 'D Brevis', 'DG Nalkande', 'B Sai Sudharsan', 'M Theekshana', 'Ramandeep Singh', 'HE van der Dussen', 'KR Sen', 'SS Prabhudessai', 'Yash Dayal', 'Shashank Singh', 'Aman Hakim Khan', 'OC McCoy', 'HR Shokeen', 'DJ Mitchell', 'B Indrajith', 'Harshit Rana', 'K Kartikeya', 'Simarjeet Singh', 'SA Abbott', 'Fazalhaq Farooqi', 'KS Sharma', 'R Sai Kishore', 'T Stubbs', 'PH Solanki', 'M Pathirana', 'R Sanjay Yadav', 'A Tomar', 'PN Mankad', 'J Little', 'RS Hangargekar', 'Sikandar Raza', 'Rahmanullah Gurbaz', 'KR Mayers', 'Mukesh Kumar', 'RR Rossouw', 'HC Brook', 'NA Saini', 'RJW Topley', 'C Green', 'MG Bracewell', 'N Wadhera', 'Arshad Khan', 'Yash Thakur', 'Abishek Porel', 'Dhruv Jurel', 'Suyash Sharma', 'SSB Magala', 'MW Short', 'Mohit Rathee', 'WD Parnell', 'YV Dhull', 'Vijaykumar Vyshak', 'Yudhvir Singh', 'Atharva Taide', 'Harpreet Singh', 'Arjun Tendulkar', 'D Jansen', 'Noor Ahmad', 'Naveen-ul-Haq', 'Liton Das', 'PD Salt', 'Mayank Dagar', 'Abdul Basith', 'Gurnoor Brar', 'AJ Hosein', 'Akash Madhwal', 'R Goyal', 'Vivrant Sharma', 'JE Root', 'MD Shanaka', 'Sanvir Singh', 'Nithish Kumar Reddy', 'H Sharma', 'R Ravindra', 'SD Hope', 'Sumit Kumar', 'MA Starc', 'N Burger', 'L Wood', 'SZ Mulani', 'Azmatullah Omarzai', 'Naman Dhir', 'G Coetzee', 'SH Johnson', 'Sameer Rizvi', 'KT Maphaka', 'M Siddharth', 'MP Yadav', 'SB Dubey', 'A Raghuvanshi', 'Ashutosh Sharma', 'Saurav Chauhan', 'Kumar Kushagra', 'BR Sharath', 'KA Maharaj', 'WG Jacks', 'J Fraser-McGurk', 'Tanush Kotian', 'Arshad Khan (2)', 'S Joseph', 'N Thushara', 'LB Williams', 'AA Kulkarni', 'RJ Gleeson', 'MJ Suthar', 'A Kamboj', 'Gulbadin Naib', 'D Ferreira', 'V Viyaskanth', 'V Kaverappa', 'T Kohler-Cadmore', 'Shivam Singh', 'Aniket Verma', 'RD Rickelton', 'R Minz', 'PVSN Raju', 'V Puthur', 'V Nigam', 'DS Rathi', 'Prince Yadav', 'Priyansh Arya', 'PWA Mulder', 'Zeeshan Ansari', 'J Overton', 'Ashwani Kumar', 'PHKD Mendis', 'Suryansh Shedge', 'E Malinga', 'SK Rasheed', 'JP Inglis', 'XC Bartlett', 'MS Bhandage', 'V Suryavanshi', 'A Mhatre', 'C Bosch', 'JG Bethell', 'Karim Janat', 'KS Rathore', 'Urvil Patel', 'M Tiwari', 'MJ Owen', 'Harsh Dubey', "W O'Rourke", 'MP Breetzke', 'Musheer Khan', 'BKG Mendis', 'Sediqullah Atal'])

In [10]:
import json

with open("data/short_name_to_full_name.json", "r", encoding="utf-8") as f:
    data2 = json.load(f)

print(type(data2))

if isinstance(data2, dict):
    print(data2.keys())

if isinstance(data2, list):
    print(data2[0])

<class 'dict'>
dict_keys(['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma', 'R Dravid', 'V Kohli', 'JH Kallis', 'CL White', 'P Kumar', 'Z Khan', 'PA Patel', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'MS Gony', 'M Muralitharan', 'KC Sangakkara', 'Yuvraj Singh', 'IK Pathan', 'B Lee', 'PP Chawla', 'S Sreesanth', 'YK Pathan', 'SR Watson', 'M Kaif', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Trivedi', 'MM Patel', 'G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwary', 'R Bhatia', 'M Manhas', 'DL Vettori', 'RV Uthappa', 'AM Nayar', 'Harbhajan Singh', 'A Nehra', 'DS Kulkarni', 'S Sohal', 'Pankaj Singh', 'DJ Bravo', 'GC Smith', 'SS Tiwary', 'AM Rahane', 'SD Chitnis', 'TM Srivastava', 'B Chipli', 'DW Steyn', 'DB Das', 'MK Pandey', 'SE Marsh', 'BJ Hodge', 'AB de Villiers', 'PJ Sangwan', 'SP Goswami', 'YV Takawale', 'S Anirudha', 'L Balaji', 'A Chopra', 'SR Tendulkar', 'DR Smith', 'TM Dilshan', 'A Mishra', 'LA Pomersbach', 'Iqbal Abdulla', 'RR Powar', 'A Mukund', 'R Ashwin', 'JP Duminy', 'Kamran Khan', 'DP Nannes', 'AM Salvi', 'RS Bopara', 'VS Malik', 'CH Gayle', 'MC Henriques', 'Anureet Singh', 'AS Raut', 'KP Appanna', 'S Tyagi', 'SB Jakati', 'NV Ojha', 'M Vijay', 'DA Warner', 'A Singh', 'M Morkel', 'GJ Bailey', 'A Mithun', 'AD Mathews', 'J Botha', 'AB McDonald', 'Y Nagar', 'CK Langeveldt', 'CA Pujara', 'OA Shah', 'AP Tare', 'AT Rayudu', 'R Sathish', 'R McLaren', 'AG Murtaza', 'AA Jhunjhunwala', 'P Dogra', 'SW Tait', 'MS Bisla', 'EJG Morgan', 'RE van der Merwe', 'S Ladda', 'Bipul Sharma', 'KA Pollard', 'S Narwal', 'UT Yadav', 'SJ Srivastava', 'FY Fazal', 'J Theron', 'KM Jadhav', 'PD Collingwood', 'KP Pietersen', 'DE Bollinger', 'SB Wagh', 'JD Unadkat', 'AP Dole', 'AG Paunikar', 'AJ Finch', 'STR Binny', 'SB Styris', 'TG Southee', 'S Randiv', 'AL Menaria', 'MA Agarwal', 'AUK Pathan', 'UBT Chand', 'DJ Jacobs', 'RG Sharma', 'JEC Franklin', 'AC Gilchrist', 'PC Valthaty', 'Sunny Singh', 'NJ Rimmington', 'BA Bhatt', 'RN ten Doeschate', 'S Nadeem', 'RJ Harris', 'R Ninan', 'S Aravind', 'Shakib Al Hasan', 'MS Wade', 'DH Yagnik', 'BJ Haddin', 'VR Aaron', 'TL Suman', 'AC Blizzard', 'CA Ingram', 'Mandeep Singh', 'AA Kazi', 'AA Chavan', 'F du Plessis', 'PP Ojha', 'GJ Maxwell', 'M de Lange', 'SA Yadav', 'JP Faulkner', 'Harmeet Singh', 'KK Cooper', 'DAJ Bracewell', 'HV Patel', 'SP Narine', 'RR Bhatkal', 'P Awana', 'CJ McKay', 'RP Singh', 'AD Russell', 'N Saini', 'DA Miller', 'Azhar Mahmood', 'P Negi', 'A Chandila', 'R Shukla', 'BW Hilfenhaus', 'Gurkeerat Singh', 'HH Gibbs', 'Sunny Gupta', 'MC Juneja', 'JJ Bumrah', 'MG Johnson', 'DT Christian', 'KK Nair', 'A Ashish Reddy', 'DB Ravi Teja', 'S Badree', 'B Laughlin', 'AS Rajpoot', 'M Vohra', 'Ankit Sharma', 'Mohammed Shami', 'R Dhawan', 'CH Morris', 'KL Rahul', 'S Kaul', 'Anand Rajan', 'MM Sharma', 'R Rampaul', 'SMSM Senanayake', 'KV Sharma', 'SV Samson', 'Q de Kock', 'BB Samantray', 'JO Holder', 'CM Gautam', 'Sandeep Sharma', 'DJG Sammy', 'Sachin Baby', 'P Suyal', 'PV Tambe', 'MG Neser', 'NM Coulter-Nile', 'CJ Anderson', 'JDS Neesham', 'WD Parnell', 'R Sharma', 'NJ Maddinson', 'S Rana', 'MA Starc', 'YS Chahal', 'AR Patel', 'KW Richardson', 'B Kumar', 'SPD Smith', 'IC Pandey', 'CA Lynn', 'BR Dunk', 'RR Rossouw', 'R Tewatia', 'Shivam Sharma', 'Imran Tahir', 'LMP Simmons', 'VH Zol', 'V Shankar', 'BCJ Cutting', 'K Santokie', 'S Gopal', 'BE Hendricks', 'Parvez Rasool', 'PJ Cummins', 'JW Hastings', 'Karanveer Singh', 'SS Iyer', 'DJ Hooda', 'KS Williamson', 'TA Boult', 'KC Cariappa', 'SA Abbott', 'J Suchith', 'RG More', 'HH Pandya', 'MJ McClenaghan', 'D Wiese', 'SN Khan', 'SN Thakur', 'GS Sandhu', 'J Yadav', 'BB Sran', 'JC Buttler', 'CR Brathwaite', 'C Munro', 'MP Stoinis', 'P Sahu', 'AF Milne', 'Mustafizur Rahman', 'Kuldeep Yadav', 'KH Pandya', 'KJ Abbott', 'MJ Guptill', 'TM Head', 'T Shamsi', 'NS Naik', 'RR Pant', 'SW Billings', 'Swapnil Singh', 'CJ Jordan', 'HM Amla', 'F Behardien', 'N Rana', 'TS Mills', 'A Choudhary', 'Rashid Khan', 'CR Woakes', 'T Natarajan', 'Vishnu Vinod', 'B Stanlake', 'C de Grandhomme', 'Mohammad Nabi', 'Mohammed Siraj', 'K Rabada', 'SP Jackson', 'MN Samuels', 'MJ Henry', 'Avesh Khan', 'IR Jaggi', 'E Lewis', 'Ishan Kishan', 'M Markande', 'DL Chahar', 'MA Wood', 'AJ Tye', 'Washington Sundar', 'K Khejroliya', 'RK Singh', 'BA Stokes', 'RA Tripathi', 'K Gowtham', 'TK Curran', 'A Dananjaya', 'JJ Roy', 'Shubman Gill', 'Shivam Mavi', 'H Klaasen', 'RK Bhui', 'JC Archer', 'PP Shaw', 'Basil Thampi', 'AD Hales', 'MK Lomror', 'IS Sodhi', 'M Ashwin', 'KM Asif', 'L Ngidi', 'DR Shorey', 'DJ Willey', 'MM Ali', 'AD Nath', 'P Chopra', 'Abhishek Sharma', 'S Lamichhane', 'KK Ahmed', 'SO Hetmyer', 'S Dube', 'Navdeep Saini', 'JM Bairstow', 'LH Ferguson', 'KMA Paul', 'Rasikh Salam', 'N Pooran', 'SM Curran', 'P Ray Barman', 'MJ Santner', 'JP Behrendorff', 'RD Chahar', 'SC Kuggeleijn', 'AS Joseph', 'S Midhun', 'HF Gurney', 'SD Lad', 'R Parag', 'JL Denly', 'LS Livingstone', 'Arshdeep Singh', 'AJ Turner', 'Harpreet Brar', 'SE Rutherford', 'O Thomas', 'AS Roy', 'S Sandeep Warrier', 'P Simran Singh', 'A Nortje', 'Ravi Bishnoi', 'D Padikkal', 'PK Garg', 'Abdul Samad', 'YBK Jaiswal', 'RD Gaikwad', 'KL Nagarkoti', 'Kartik Tyagi', 'N Jagadeesan', 'A Zampa', 'JR Hazlewood', 'P Dubey', 'M Jansen', 'RM Patidar', 'KA Jamieson', 'JA Richardson', 'RP Meredith', 'C Sakariya', 'Lalit Yadav', 'Virat Singh', 'Jalaj S Saxena', 'LI Meriwala', 'FA Allen', 'DR Sams', 'Anuj Rawat', 'DJ Malan', 'KS Bharat', 'VR Iyer', 'Umran Malik', 'GD Phillips', 'Akash Singh', 'GHS Garton', 'AK Markram', 'K Yadav', 'NT Ellis', 'RV Patel', 'TL Seifert', 'Anmolpreet Singh', 'IC Porel', 'AU Rashid', 'TH David', 'DP Conway', 'TU Deshpande', 'R Powell', 'Akash Deep', 'RA Bawa', 'OF Smith', 'A Badoni', 'Mohsin Khan', 'A Manohar', 'R Shepherd', 'D Pretorius', 'Mukesh Choudhary', 'JM Sharma', 'VG Arora', 'D Brevis', 'DG Nalkande', 'M Theekshana', 'Shashank Singh', 'Ramandeep Singh', 'KR Sen', 'SS Prabhudessai', 'Yash Dayal', 'Aman Hakim Khan', 'MR Marsh', 'OC McCoy', 'HR Shokeen', 'DJ Mitchell', 'B Indrajith', 'Harshit Rana', 'K Kartikeya', 'Simarjeet Singh', 'Fazalhaq Farooqi', 'KS Sharma', 'T Stubbs', 'PH Solanki', 'M Pathirana', 'A Tomar', 'PN Mankad', 'RS Hangargekar', 'J Little', 'Sikandar Raza', 'Rahmanullah Gurbaz', 'KR Mayers', 'Mukesh Kumar', 'NA Saini', 'HC Brook', 'C Green', 'N Wadhera', 'MG Bracewell', 'RJW Topley', 'Yash Thakur', 'Abishek Porel', 'Dhruv Jurel', 'Suyash Sharma', 'SSB Magala', 'MW Short', 'Mohit Rathee', 'YV Dhull', 'Vijaykumar Vyshak', 'Yudhvir Singh', 'Atharva Taide', 'Arjun Tendulkar', 'D Jansen', 'Noor Ahmad', 'Liton Das', 'PD Salt', 'Mayank Dagar', 'Gurnoor Brar', 'AJ Hosein', 'Akash Madhwal', 'R Goyal', 'JE Root', 'Vivrant Sharma', 'Sanvir Singh', 'Nithish Kumar Reddy', 'H Sharma', 'R Ravindra', 'Sameer Rizvi', 'SD Hope', 'Sumit Kumar', 'N Burger', 'Azmatullah Omarzai', 'SH Johnson', 'L Wood', 'Naman Dhir', 'G Coetzee', 'SZ Mulani', 'KT Maphaka', 'A Raghuvanshi', 'MP Yadav', 'M Siddharth', 'SB Dubey', 'Ashutosh Sharma', 'Kumar Kushagra', 'BR Sharath', 'KA Maharaj', 'WG Jacks', 'J Fraser-McGurk', 'Tanush Kotian', 'S Joseph', 'N Thushara', 'LB Williams', 'AA Kulkarni', 'RJ Gleeson', 'MJ Suthar', 'A Kamboj', 'Gulbadin Naib', 'D Ferreira', 'V Viyaskanth', 'V Kaverappa', 'T Kohler-Cadmore', 'Shivam Singh', 'Aniket Verma', 'R Minz', 'Prince Yadav', 'V Nigam', 'Priyansh Arya', 'Suryansh Shedge', 'M Shahrukh Khan', 'Zeeshan Ansari', 'J Overton', 'Ashwani Kumar', 'Himmat Singh', 'E Malinga', 'SK Rasheed', 'JP Inglis', 'XC Bartlett', 'MS Bhandage', 'V Suryavanshi', 'A Mhatre', 'Karim Janat', 'KS Rathore', 'Urvil Patel', 'M Tiwari', 'MJ Owen', 'Harsh Dubey', 'Sediqullah Atal', 'MP Breetzke', 'Musheer Khan'])

In [13]:
print(type(data1))
print(data1.keys())   # if dict

<class 'dict'>
dict_keys(['LMP Simmons', 'RP Singh', 'RG Sharma', 'I Sharma', 'HH Pandya', 'JC Buttler', 'MR Marsh', 'AT Rayudu', 'KA Pollard', 'R Bhatia', 'S Gopal', 'M Ashwin', 'Harbhajan Singh', 'R Ashwin', 'R Vinay Kumar', 'MJ McClenaghan', 'AM Rahane', 'F du Plessis', 'JJ Bumrah', 'KP Pietersen', 'MA Agarwal', 'AD Russell', 'Q de Kock', 'UT Yadav', 'SS Iyer', 'JW Hastings', 'KK Nair', 'SV Samson', 'P Negi', 'C Munro', 'GB Hogg', 'PP Chawla', 'CR Brathwaite', 'CH Morris', 'NM Coulter-Nile', 'A Mishra', 'Z Khan', 'RV Uthappa', 'G Gambhir', 'MK Pandey', 'M Vijay', 'P Kumar', 'M Vohra', 'PJ Sangwan', 'JP Faulkner', 'S Ladda', 'RA Jadeja', 'DA Miller', 'DJ Bravo', 'GJ Maxwell', 'WP Saha', 'MP Stoinis', 'AR Patel', 'AJ Finch', 'Sandeep Sharma', 'BB McCullum', 'MG Johnson', 'SK Raina', 'MM Sharma', 'KD Karthik', 'P Sahu', 'Ishan Kishan', 'CH Gayle', 'A Nehra', 'V Kohli', 'B Kumar', 'AB de Villiers', 'Mustafizur Rahman', 'MC Henriques', 'KV Sharma', 'A Ashish Reddy', 'SR Watson', 'KM Jadhav', 'SN Khan', 'DA Warner', 'AF Milne', 'S Dhawan', 'Parvez Rasool', 'HV Patel', 'YS Chahal', 'NV Ojha', 'DJ Hooda', 'EJG Morgan', 'TG Southee', 'J Suchith', 'YK Pathan', 'SA Yadav', 'PA Patel', 'Kuldeep Yadav', 'SB Jakati', 'PV Tambe', 'SPD Smith', 'MS Dhoni', 'SE Marsh', 'J Yadav', 'M Morkel', 'Shakib Al Hasan', 'SP Narine', 'BB Sran', 'DS Kulkarni', 'KH Pandya', 'AD Nath', 'KJ Abbott', 'NLTC Perera', 'IK Pathan', 'Ankit Sharma', 'Mohammed Shami', 'D Wiese', 'S Aravind', 'JP Duminy', 'MJ Guptill', 'Bipul Sharma', 'KL Rahul', 'TM Head', 'STR Binny', 'KW Richardson', 'VR Aaron', 'Iqbal Abdulla', 'DW Steyn', 'T Shamsi', 'Imran Tahir', 'NS Naik', 'R Dhawan', 'AP Tare', 'DR Smith', 'R Sathish', 'JA Morkel', 'AB Dinda', 'S Nadeem', 'RR Pant', 'CA Lynn', 'JD Unadkat', 'SS Tiwary', 'S Kaushik', 'JO Holder', 'SW Billings', 'KS Williamson', 'Sachin Baby', 'Gurkeerat Singh', 'KC Cariappa', 'PSP Handscomb', 'SM Boland', 'Swapnil Singh', 'UT Khawaja', 'Yuvraj Singh', 'CJ Jordan', 'GJ Bailey', 'A Zampa', 'HM Amla', 'Anureet Singh', 'F Behardien', 'N Rana', 'UBT Chand', 'AS Rajpoot', 'BCJ Cutting', 'DL Chahar', 'ER Dwivedi', 'TA Boult', 'TS Mills', 'A Choudhary', 'Mandeep Singh', 'Rashid Khan', 'BA Stokes', 'JJ Roy', 'CR Woakes', 'MS Gony', 'T Natarajan', 'MK Tiwary', 'DT Christian', 'RD Chahar', 'PJ Cummins', 'Vishnu Vinod', 'B Stanlake', 'Basil Thampi', 'Tejas Baroka', 'SL Malinga', 'CJ Anderson', 'RA Tripathi', 'V Shankar', 'C de Grandhomme', 'S Badree', 'AJ Tye', 'SN Thakur', 'LH Ferguson', 'MM Patel', 'AD Mathews', 'Mohammad Nabi', 'S Kaul', 'Mohammed Siraj', 'K Rabada', 'Washington Sundar', 'SS Agarwal', 'NB Singh', 'DM Bravo', 'Ankit Soni', 'AR Bawne', 'SP Jackson', 'MN Samuels', 'R Tewatia', 'MJ Henry', 'Avesh Khan', 'IR Jaggi', 'E Lewis', 'MA Wood', 'M Markande', 'Mujeeb Ur Rahman', 'K Khejroliya', 'RK Singh', 'DJM Short', 'K Gowtham', 'B Laughlin', 'TK Curran', 'A Dananjaya', 'Shubman Gill', 'Shivam Mavi', 'H Klaasen', 'RK Bhui', 'JC Archer', 'LE Plunkett', 'PP Shaw', 'AD Hales', 'IS Sodhi', 'MK Lomror', 'L Ngidi', 'KM Asif', 'DJ Willey', 'DR Shorey', 'M Prasidh Krishna', 'MM Ali', 'P Chopra', 'JPR Scantlebury-Searles', 'Abhishek Sharma', 'S Lamichhane', 'CJ Dala', 'SP Goswami', 'KK Ahmed', 'SO Hetmyer', 'S Dube', 'Navdeep Saini', 'JM Bairstow', 'Rasikh Salam', 'CA Ingram', 'KMA Paul', 'N Pooran', 'SM Curran', 'CV Varun', 'GC Viljoen', 'GH Vihari', 'P Ray Barman', 'MJ Santner', 'JP Behrendorff', 'SC Kuggeleijn', 'AS Joseph', 'HF Gurney', 'S Midhun', 'SD Lad', 'R Parag', 'JL Denly', 'LS Livingstone', 'Arshdeep Singh', 'AJ Turner', 'SE Rutherford', 'Harpreet Brar', 'Y Prithvi Raj', 'O Thomas', 'AS Roy', 'S Sandeep Warrier', 'P Simran Singh', 'JL Pattinson', 'SS Cottrell', 'Ravi Bishnoi', 'A Nortje', 'T Banton', 'I Udana', 'D Padikkal', 'YBK Jaiswal', 'RD Gaikwad', 'TU Deshpande', 'KL Nagarkoti', 'Abdul Samad', 'PK Garg', 'JR Philippe', 'Kartik Tyagi', 'JDS Neesham', 'DR Sams', 'Shahbaz Ahmed', 'AT Carey', 'N Jagadeesan', 'JR Hazlewood', 'CJ Green', 'P Dubey', 'Monu Kumar', 'KA Jamieson', 'M Jansen', 'RM Patidar', 'C Sakariya', 'M Shahrukh Khan', 'JA Richardson', 'RP Meredith', 'Lalit Yadav', 'Virat Singh', 'LI Meriwala', 'Jalaj S Saxena', 'FA Allen', 'DJ Malan', 'KS Bharat', 'PWH de Silva', 'VR Iyer', 'Umran Malik', 'Akash Singh', 'GD Phillips', 'AK Markram', 'GHS Garton', 'K Yadav', 'NT Ellis', 'RV Patel', 'TL Seifert', 'Anmolpreet Singh', 'Anuj Rawat', 'IC Porel', 'AU Rashid', 'TH David', 'DP Conway', 'Tilak Varma', 'R Powell', 'OF Smith', 'Akash Deep', 'PBB Rajapaksa', 'RA Bawa', 'A Badoni', 'PVD Chameera', 'MS Wade', 'Mohsin Khan', 'A Manohar', 'R Shepherd', 'D Pretorius', 'Mukesh Choudhary', 'JM Sharma', 'VG Arora', 'D Brevis', 'DG Nalkande', 'B Sai Sudharsan', 'M Theekshana', 'Ramandeep Singh', 'HE van der Dussen', 'KR Sen', 'SS Prabhudessai', 'Yash Dayal', 'Shashank Singh', 'Aman Hakim Khan', 'OC McCoy', 'HR Shokeen', 'DJ Mitchell', 'B Indrajith', 'Harshit Rana', 'K Kartikeya', 'Simarjeet Singh', 'SA Abbott', 'Fazalhaq Farooqi', 'KS Sharma', 'R Sai Kishore', 'T Stubbs', 'PH Solanki', 'M Pathirana', 'R Sanjay Yadav', 'A Tomar', 'PN Mankad', 'J Little', 'RS Hangargekar', 'Sikandar Raza', 'Rahmanullah Gurbaz', 'KR Mayers', 'Mukesh Kumar', 'RR Rossouw', 'HC Brook', 'NA Saini', 'RJW Topley', 'C Green', 'MG Bracewell', 'N Wadhera', 'Arshad Khan', 'Yash Thakur', 'Abishek Porel', 'Dhruv Jurel', 'Suyash Sharma', 'SSB Magala', 'MW Short', 'Mohit Rathee', 'WD Parnell', 'YV Dhull', 'Vijaykumar Vyshak', 'Yudhvir Singh', 'Atharva Taide', 'Harpreet Singh', 'Arjun Tendulkar', 'D Jansen', 'Noor Ahmad', 'Naveen-ul-Haq', 'Liton Das', 'PD Salt', 'Mayank Dagar', 'Abdul Basith', 'Gurnoor Brar', 'AJ Hosein', 'Akash Madhwal', 'R Goyal', 'Vivrant Sharma', 'JE Root', 'MD Shanaka', 'Sanvir Singh', 'Nithish Kumar Reddy', 'H Sharma', 'R Ravindra', 'SD Hope', 'Sumit Kumar', 'MA Starc', 'N Burger', 'L Wood', 'SZ Mulani', 'Azmatullah Omarzai', 'Naman Dhir', 'G Coetzee', 'SH Johnson', 'Sameer Rizvi', 'KT Maphaka', 'M Siddharth', 'MP Yadav', 'SB Dubey', 'A Raghuvanshi', 'Ashutosh Sharma', 'Saurav Chauhan', 'Kumar Kushagra', 'BR Sharath', 'KA Maharaj', 'WG Jacks', 'J Fraser-McGurk', 'Tanush Kotian', 'Arshad Khan (2)', 'S Joseph', 'N Thushara', 'LB Williams', 'AA Kulkarni', 'RJ Gleeson', 'MJ Suthar', 'A Kamboj', 'Gulbadin Naib', 'D Ferreira', 'V Viyaskanth', 'V Kaverappa', 'T Kohler-Cadmore', 'Shivam Singh', 'Aniket Verma', 'RD Rickelton', 'R Minz', 'PVSN Raju', 'V Puthur', 'V Nigam', 'DS Rathi', 'Prince Yadav', 'Priyansh Arya', 'PWA Mulder', 'Zeeshan Ansari', 'J Overton', 'Ashwani Kumar', 'PHKD Mendis', 'Suryansh Shedge', 'E Malinga', 'SK Rasheed', 'JP Inglis', 'XC Bartlett', 'MS Bhandage', 'V Suryavanshi', 'A Mhatre', 'C Bosch', 'JG Bethell', 'Karim Janat', 'KS Rathore', 'Urvil Patel', 'M Tiwari', 'MJ Owen', 'Harsh Dubey', "W O'Rourke", 'MP Breetzke', 'Musheer Khan', 'BKG Mendis', 'Sediqullah Atal'])

In [14]:
print(type(data2))
print(data2.keys())   # if dict

<class 'dict'>
dict_keys(['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma', 'R Dravid', 'V Kohli', 'JH Kallis', 'CL White', 'P Kumar', 'Z Khan', 'PA Patel', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'MS Gony', 'M Muralitharan', 'KC Sangakkara', 'Yuvraj Singh', 'IK Pathan', 'B Lee', 'PP Chawla', 'S Sreesanth', 'YK Pathan', 'SR Watson', 'M Kaif', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Trivedi', 'MM Patel', 'G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwary', 'R Bhatia', 'M Manhas', 'DL Vettori', 'RV Uthappa', 'AM Nayar', 'Harbhajan Singh', 'A Nehra', 'DS Kulkarni', 'S Sohal', 'Pankaj Singh', 'DJ Bravo', 'GC Smith', 'SS Tiwary', 'AM Rahane', 'SD Chitnis', 'TM Srivastava', 'B Chipli', 'DW Steyn', 'DB Das', 'MK Pandey', 'SE Marsh', 'BJ Hodge', 'AB de Villiers', 'PJ Sangwan', 'SP Goswami', 'YV Takawale', 'S Anirudha', 'L Balaji', 'A Chopra', 'SR Tendulkar', 'DR Smith', 'TM Dilshan', 'A Mishra', 'LA Pomersbach', 'Iqbal Abdulla', 'RR Powar', 'A Mukund', 'R Ashwin', 'JP Duminy', 'Kamran Khan', 'DP Nannes', 'AM Salvi', 'RS Bopara', 'VS Malik', 'CH Gayle', 'MC Henriques', 'Anureet Singh', 'AS Raut', 'KP Appanna', 'S Tyagi', 'SB Jakati', 'NV Ojha', 'M Vijay', 'DA Warner', 'A Singh', 'M Morkel', 'GJ Bailey', 'A Mithun', 'AD Mathews', 'J Botha', 'AB McDonald', 'Y Nagar', 'CK Langeveldt', 'CA Pujara', 'OA Shah', 'AP Tare', 'AT Rayudu', 'R Sathish', 'R McLaren', 'AG Murtaza', 'AA Jhunjhunwala', 'P Dogra', 'SW Tait', 'MS Bisla', 'EJG Morgan', 'RE van der Merwe', 'S Ladda', 'Bipul Sharma', 'KA Pollard', 'S Narwal', 'UT Yadav', 'SJ Srivastava', 'FY Fazal', 'J Theron', 'KM Jadhav', 'PD Collingwood', 'KP Pietersen', 'DE Bollinger', 'SB Wagh', 'JD Unadkat', 'AP Dole', 'AG Paunikar', 'AJ Finch', 'STR Binny', 'SB Styris', 'TG Southee', 'S Randiv', 'AL Menaria', 'MA Agarwal', 'AUK Pathan', 'UBT Chand', 'DJ Jacobs', 'RG Sharma', 'JEC Franklin', 'AC Gilchrist', 'PC Valthaty', 'Sunny Singh', 'NJ Rimmington', 'BA Bhatt', 'RN ten Doeschate', 'S Nadeem', 'RJ Harris', 'R Ninan', 'S Aravind', 'Shakib Al Hasan', 'MS Wade', 'DH Yagnik', 'BJ Haddin', 'VR Aaron', 'TL Suman', 'AC Blizzard', 'CA Ingram', 'Mandeep Singh', 'AA Kazi', 'AA Chavan', 'F du Plessis', 'PP Ojha', 'GJ Maxwell', 'M de Lange', 'SA Yadav', 'JP Faulkner', 'Harmeet Singh', 'KK Cooper', 'DAJ Bracewell', 'HV Patel', 'SP Narine', 'RR Bhatkal', 'P Awana', 'CJ McKay', 'RP Singh', 'AD Russell', 'N Saini', 'DA Miller', 'Azhar Mahmood', 'P Negi', 'A Chandila', 'R Shukla', 'BW Hilfenhaus', 'Gurkeerat Singh', 'HH Gibbs', 'Sunny Gupta', 'MC Juneja', 'JJ Bumrah', 'MG Johnson', 'DT Christian', 'KK Nair', 'A Ashish Reddy', 'DB Ravi Teja', 'S Badree', 'B Laughlin', 'AS Rajpoot', 'M Vohra', 'Ankit Sharma', 'Mohammed Shami', 'R Dhawan', 'CH Morris', 'KL Rahul', 'S Kaul', 'Anand Rajan', 'MM Sharma', 'R Rampaul', 'SMSM Senanayake', 'KV Sharma', 'SV Samson', 'Q de Kock', 'BB Samantray', 'JO Holder', 'CM Gautam', 'Sandeep Sharma', 'DJG Sammy', 'Sachin Baby', 'P Suyal', 'PV Tambe', 'MG Neser', 'NM Coulter-Nile', 'CJ Anderson', 'JDS Neesham', 'WD Parnell', 'R Sharma', 'NJ Maddinson', 'S Rana', 'MA Starc', 'YS Chahal', 'AR Patel', 'KW Richardson', 'B Kumar', 'SPD Smith', 'IC Pandey', 'CA Lynn', 'BR Dunk', 'RR Rossouw', 'R Tewatia', 'Shivam Sharma', 'Imran Tahir', 'LMP Simmons', 'VH Zol', 'V Shankar', 'BCJ Cutting', 'K Santokie', 'S Gopal', 'BE Hendricks', 'Parvez Rasool', 'PJ Cummins', 'JW Hastings', 'Karanveer Singh', 'SS Iyer', 'DJ Hooda', 'KS Williamson', 'TA Boult', 'KC Cariappa', 'SA Abbott', 'J Suchith', 'RG More', 'HH Pandya', 'MJ McClenaghan', 'D Wiese', 'SN Khan', 'SN Thakur', 'GS Sandhu', 'J Yadav', 'BB Sran', 'JC Buttler', 'CR Brathwaite', 'C Munro', 'MP Stoinis', 'P Sahu', 'AF Milne', 'Mustafizur Rahman', 'Kuldeep Yadav', 'KH Pandya', 'KJ Abbott', 'MJ Guptill', 'TM Head', 'T Shamsi', 'NS Naik', 'RR Pant', 'SW Billings', 'Swapnil Singh', 'CJ Jordan', 'HM Amla', 'F Behardien', 'N Rana', 'TS Mills', 'A Choudhary', 'Rashid Khan', 'CR Woakes', 'T Natarajan', 'Vishnu Vinod', 'B Stanlake', 'C de Grandhomme', 'Mohammad Nabi', 'Mohammed Siraj', 'K Rabada', 'SP Jackson', 'MN Samuels', 'MJ Henry', 'Avesh Khan', 'IR Jaggi', 'E Lewis', 'Ishan Kishan', 'M Markande', 'DL Chahar', 'MA Wood', 'AJ Tye', 'Washington Sundar', 'K Khejroliya', 'RK Singh', 'BA Stokes', 'RA Tripathi', 'K Gowtham', 'TK Curran', 'A Dananjaya', 'JJ Roy', 'Shubman Gill', 'Shivam Mavi', 'H Klaasen', 'RK Bhui', 'JC Archer', 'PP Shaw', 'Basil Thampi', 'AD Hales', 'MK Lomror', 'IS Sodhi', 'M Ashwin', 'KM Asif', 'L Ngidi', 'DR Shorey', 'DJ Willey', 'MM Ali', 'AD Nath', 'P Chopra', 'Abhishek Sharma', 'S Lamichhane', 'KK Ahmed', 'SO Hetmyer', 'S Dube', 'Navdeep Saini', 'JM Bairstow', 'LH Ferguson', 'KMA Paul', 'Rasikh Salam', 'N Pooran', 'SM Curran', 'P Ray Barman', 'MJ Santner', 'JP Behrendorff', 'RD Chahar', 'SC Kuggeleijn', 'AS Joseph', 'S Midhun', 'HF Gurney', 'SD Lad', 'R Parag', 'JL Denly', 'LS Livingstone', 'Arshdeep Singh', 'AJ Turner', 'Harpreet Brar', 'SE Rutherford', 'O Thomas', 'AS Roy', 'S Sandeep Warrier', 'P Simran Singh', 'A Nortje', 'Ravi Bishnoi', 'D Padikkal', 'PK Garg', 'Abdul Samad', 'YBK Jaiswal', 'RD Gaikwad', 'KL Nagarkoti', 'Kartik Tyagi', 'N Jagadeesan', 'A Zampa', 'JR Hazlewood', 'P Dubey', 'M Jansen', 'RM Patidar', 'KA Jamieson', 'JA Richardson', 'RP Meredith', 'C Sakariya', 'Lalit Yadav', 'Virat Singh', 'Jalaj S Saxena', 'LI Meriwala', 'FA Allen', 'DR Sams', 'Anuj Rawat', 'DJ Malan', 'KS Bharat', 'VR Iyer', 'Umran Malik', 'GD Phillips', 'Akash Singh', 'GHS Garton', 'AK Markram', 'K Yadav', 'NT Ellis', 'RV Patel', 'TL Seifert', 'Anmolpreet Singh', 'IC Porel', 'AU Rashid', 'TH David', 'DP Conway', 'TU Deshpande', 'R Powell', 'Akash Deep', 'RA Bawa', 'OF Smith', 'A Badoni', 'Mohsin Khan', 'A Manohar', 'R Shepherd', 'D Pretorius', 'Mukesh Choudhary', 'JM Sharma', 'VG Arora', 'D Brevis', 'DG Nalkande', 'M Theekshana', 'Shashank Singh', 'Ramandeep Singh', 'KR Sen', 'SS Prabhudessai', 'Yash Dayal', 'Aman Hakim Khan', 'MR Marsh', 'OC McCoy', 'HR Shokeen', 'DJ Mitchell', 'B Indrajith', 'Harshit Rana', 'K Kartikeya', 'Simarjeet Singh', 'Fazalhaq Farooqi', 'KS Sharma', 'T Stubbs', 'PH Solanki', 'M Pathirana', 'A Tomar', 'PN Mankad', 'RS Hangargekar', 'J Little', 'Sikandar Raza', 'Rahmanullah Gurbaz', 'KR Mayers', 'Mukesh Kumar', 'NA Saini', 'HC Brook', 'C Green', 'N Wadhera', 'MG Bracewell', 'RJW Topley', 'Yash Thakur', 'Abishek Porel', 'Dhruv Jurel', 'Suyash Sharma', 'SSB Magala', 'MW Short', 'Mohit Rathee', 'YV Dhull', 'Vijaykumar Vyshak', 'Yudhvir Singh', 'Atharva Taide', 'Arjun Tendulkar', 'D Jansen', 'Noor Ahmad', 'Liton Das', 'PD Salt', 'Mayank Dagar', 'Gurnoor Brar', 'AJ Hosein', 'Akash Madhwal', 'R Goyal', 'JE Root', 'Vivrant Sharma', 'Sanvir Singh', 'Nithish Kumar Reddy', 'H Sharma', 'R Ravindra', 'Sameer Rizvi', 'SD Hope', 'Sumit Kumar', 'N Burger', 'Azmatullah Omarzai', 'SH Johnson', 'L Wood', 'Naman Dhir', 'G Coetzee', 'SZ Mulani', 'KT Maphaka', 'A Raghuvanshi', 'MP Yadav', 'M Siddharth', 'SB Dubey', 'Ashutosh Sharma', 'Kumar Kushagra', 'BR Sharath', 'KA Maharaj', 'WG Jacks', 'J Fraser-McGurk', 'Tanush Kotian', 'S Joseph', 'N Thushara', 'LB Williams', 'AA Kulkarni', 'RJ Gleeson', 'MJ Suthar', 'A Kamboj', 'Gulbadin Naib', 'D Ferreira', 'V Viyaskanth', 'V Kaverappa', 'T Kohler-Cadmore', 'Shivam Singh', 'Aniket Verma', 'R Minz', 'Prince Yadav', 'V Nigam', 'Priyansh Arya', 'Suryansh Shedge', 'M Shahrukh Khan', 'Zeeshan Ansari', 'J Overton', 'Ashwani Kumar', 'Himmat Singh', 'E Malinga', 'SK Rasheed', 'JP Inglis', 'XC Bartlett', 'MS Bhandage', 'V Suryavanshi', 'A Mhatre', 'Karim Janat', 'KS Rathore', 'Urvil Patel', 'M Tiwari', 'MJ Owen', 'Harsh Dubey', 'Sediqullah Atal', 'MP Breetzke', 'Musheer Khan'])

In [15]:
first_player = list(data1.keys())[0]

print("Player:", first_player)
print(data1[first_player])

Player: LMP Simmons
{'2016': {'Total_Bt_Runs': 8, 'Total_Bt_Balls': 8, 'Total_Bw_Runs': 0, 'Total_Bw_Balls': 0, 'Bt_Avg': 8.0, 'Bt_strike_rate': 100.0, 'Bw_economy': 0, 'Bw_wicket_per_match': 0.0, 'Bt_Runs': [8], 'Bt_Balls': [8], 'Bw_Runs': [0], 'Bw_Balls': [0], 'Bt_four': [0], 'Bt_six': [1], 'Bt_Wickets': [1], 'Bw_Wickets': [0], 'Total_Matches': 1}, '2017': {'Total_Bt_Runs': 137, 'Total_Bt_Balls': 116, 'Total_Bw_Runs': 0, 'Total_Bw_Balls': 0, 'Bt_Avg': 19.57, 'Bt_strike_rate': 118.1, 'Bw_economy': 0, 'Bw_wicket_per_match': 0.0, 'Bt_Runs': [66, 1, 59, 0, 5, 3, 3], 'Bt_Balls': [44, 5, 33, 5, 15, 6, 8], 'Bw_Runs': [0, 0, 0, 0, 0, 0, 0], 'Bw_Balls': [0, 0, 0, 0, 0, 0, 0], 'Bt_four': [5, 0, 5, 0, 0, 0, 0], 'Bt_six': [4, 0, 4, 0, 0, 0, 0], 'Bt_Wickets': [1, 1, 1, 1, 1, 1, 1], 'Bw_Wickets': [0, 0, 0, 0, 0, 0, 0], 'Total_Matches': 7}}

In [16]:
first_player = list(data2.keys())[0]

print("Player:", first_player)
print(data2[first_player])

Player: SC Ganguly
Sourav Ganguly

In [17]:
first_player = list(data1.keys())[0]

print(type(data1[first_player]))

<class 'dict'>

In [18]:
first_player = list(data2.keys())[0]

print(type(data2[first_player]))

<class 'str'>

In [20]:
data1[first_player]

KeyError: 'SC Ganguly'

In [22]:
data2[first_player]

'Sourav Ganguly'

In [23]:
first_player1 = list(data1.keys())[0]

print(first_player1)
print(type(data1[first_player1]))
print(data1[first_player1])

LMP Simmons
<class 'dict'>
{'2016': {'Total_Bt_Runs': 8, 'Total_Bt_Balls': 8, 'Total_Bw_Runs': 0, 'Total_Bw_Balls': 0, 'Bt_Avg': 8.0, 'Bt_strike_rate': 100.0, 'Bw_economy': 0, 'Bw_wicket_per_match': 0.0, 'Bt_Runs': [8], 'Bt_Balls': [8], 'Bw_Runs': [0], 'Bw_Balls': [0], 'Bt_four': [0], 'Bt_six': [1], 'Bt_Wickets': [1], 'Bw_Wickets': [0], 'Total_Matches': 1}, '2017': {'Total_Bt_Runs': 137, 'Total_Bt_Balls': 116, 'Total_Bw_Runs': 0, 'Total_Bw_Balls': 0, 'Bt_Avg': 19.57, 'Bt_strike_rate': 118.1, 'Bw_economy': 0, 'Bw_wicket_per_match': 0.0, 'Bt_Runs': [66, 1, 59, 0, 5, 3, 3], 'Bt_Balls': [44, 5, 33, 5, 15, 6, 8], 'Bw_Runs': [0, 0, 0, 0, 0, 0, 0], 'Bw_Balls': [0, 0, 0, 0, 0, 0, 0], 'Bt_four': [5, 0, 5, 0, 0, 0, 0], 'Bt_six': [4, 0, 4, 0, 0, 0, 0], 'Bt_Wickets': [1, 1, 1, 1, 1, 1, 1], 'Bw_Wickets': [0, 0, 0, 0, 0, 0, 0], 'Total_Matches': 7}}

In [24]:
first_player2 = list(data2.keys())[0]

print(first_player2)
print(type(data2[first_player2]))
print(data2[first_player2])

SC Ganguly
<class 'str'>
Sourav Ganguly

In [25]:
print(len(data1))
print(len(data2))

486
557

In [26]:
first_player1 = list(data1.keys())[0]

print(first_player1)
print(type(data1[first_player1]))
print(data1[first_player1])

LMP Simmons
<class 'dict'>
{'2016': {'Total_Bt_Runs': 8, 'Total_Bt_Balls': 8, 'Total_Bw_Runs': 0, 'Total_Bw_Balls': 0, 'Bt_Avg': 8.0, 'Bt_strike_rate': 100.0, 'Bw_economy': 0, 'Bw_wicket_per_match': 0.0, 'Bt_Runs': [8], 'Bt_Balls': [8], 'Bw_Runs': [0], 'Bw_Balls': [0], 'Bt_four': [0], 'Bt_six': [1], 'Bt_Wickets': [1], 'Bw_Wickets': [0], 'Total_Matches': 1}, '2017': {'Total_Bt_Runs': 137, 'Total_Bt_Balls': 116, 'Total_Bw_Runs': 0, 'Total_Bw_Balls': 0, 'Bt_Avg': 19.57, 'Bt_strike_rate': 118.1, 'Bw_economy': 0, 'Bw_wicket_per_match': 0.0, 'Bt_Runs': [66, 1, 59, 0, 5, 3, 3], 'Bt_Balls': [44, 5, 33, 5, 15, 6, 8], 'Bw_Runs': [0, 0, 0, 0, 0, 0, 0], 'Bw_Balls': [0, 0, 0, 0, 0, 0, 0], 'Bt_four': [5, 0, 5, 0, 0, 0, 0], 'Bt_six': [4, 0, 4, 0, 0, 0, 0], 'Bt_Wickets': [1, 1, 1, 1, 1, 1, 1], 'Bw_Wickets': [0, 0, 0, 0, 0, 0, 0], 'Total_Matches': 7}}

# CONVERT JSON TO DATAFRAME

In [28]:
import pandas as pd

rows = []

for player, seasons in data1.items():

    for season, stats in seasons.items():

        rows.append({
            "Player": player,
            "Season": season,
            "Runs": stats["Total_Bt_Runs"],
            "Balls": stats["Total_Bt_Balls"],
            "Batting_Avg": stats["Bt_Avg"],
            "Strike_Rate": stats["Bt_strike_rate"],
            "Economy": stats["Bw_economy"],
            "Wickets_Per_Match": stats["Bw_wicket_per_match"],
            "Matches": stats["Total_Matches"]
        })

df = pd.DataFrame(rows)

print(df.shape)
df.head()

(1754, 9)

,Player,Season,Runs,Balls,Batting_Avg,Strike_Rate,Economy,Wickets_Per_Match,Matches
0,LMP Simmons,2016,8,8,8.00,100.00,0.00,0.00,1
1,LMP Simmons,2017,137,116,19.57,118.10,0.00,0.00,7
2,RP Singh,2016,0,0,0.00,0.00,8.45,0.75,4
3,RG Sharma,2016,489,372,44.45,131.45,0.00,0.00,14
4,RG Sharma,2017,333,278,23.79,119.78,0.00,0.00,16

## Step 2: Check Data

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1754 entries, 0 to 1753
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             1754 non-null   object
 1   Season             1754 non-null   object
 2   Runs               1754 non-null   int64
 3   Balls              1754 non-null   int64
 4   Batting_Avg        1754 non-null   float64
 5   Strike_Rate        1754 non-null   float64
 6   Economy            1754 non-null   float64
 7   Wickets_Per_Match  1754 non-null   float64
 8   Matches            1754 non-null   int64
dtypes: float64(4), int64(3), object(2)
memory usage: 123.5+ KB

In [31]:
df.describe()

,Runs,Balls,Batting_Avg,Strike_Rate,Economy,Wickets_Per_Match,Matches
count,1754.000000,1754.000000,1754.000000,1754.000000,1754.000000,1754.000000,1754.000000
mean,118.201824,88.770239,16.659521,96.617320,5.694014,0.484886,8.103193
std,162.139550,115.524248,15.803838,59.068367,4.588025,0.567045,4.978008
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,3.000000,5.000000,2.062500,53.850000,0.000000,0.000000,3.000000
50%,33.000000,30.000000,13.400000,111.650000,7.290000,0.250000,8.000000
75%,188.750000,142.750000,26.615000,136.360000,8.777500,1.000000,13.000000
max,973.000000,655.000000,102.000000,400.000000,36.000000,4.000000,18.000000

In [32]:
df.head()

,Player,Season,Runs,Balls,Batting_Avg,Strike_Rate,Economy,Wickets_Per_Match,Matches
0,LMP Simmons,2016,8,8,8.00,100.00,0.00,0.00,1
1,LMP Simmons,2017,137,116,19.57,118.10,0.00,0.00,7
2,RP Singh,2016,0,0,0.00,0.00,8.45,0.75,4
3,RG Sharma,2016,489,372,44.45,131.45,0.00,0.00,14
4,RG Sharma,2017,333,278,23.79,119.78,0.00,0.00,16

## Step 3: Create Our Target Variable


For a fast project, we'll define:

High_Performer = 1

if:

Runs >= 300

Otherwise:

High_Performer = 0

In [33]:
df["High_Performer"] = (
    df["Runs"] >= 300
).astype(int)

In [34]:
df["High_Performer"].value_counts()

High_Performer
0    1485
1     269
Name: count, dtype: int64

In [35]:
df.shape

(1754, 10)

## Columns

| Column            | Meaning             |
| ----------------- | ------------------- |
| Player            | Player Name         |
| Season            | IPL Season          |
| Runs              | Total Runs          |
| Balls             | Total Balls Faced   |
| Batting_Avg       | Batting Average     |
| Strike_Rate       | Strike Rate         |
| Economy           | Bowling Economy     |
| Wickets_Per_Match | Bowling Performance |
| Matches           | Matches Played      |

###Why 300 Runs?

- In IPL:

- < 100 → Poor season
- 100–300 → Average season
- 300+ → Good season
- 500+ → Excellent season

- 300 is a reasonable business threshold.

### In interviews you can say:

- Players scoring 300 or more runs in a season were considered high performers because they contribute consistently throughout the tournament.

# EDA